apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: saswatcloud/order-service:2.0
          ports:
            - containerPort: 8080
          env:
            - name: BILLING_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: billingServiceBaseUrl
#            - name: USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: mongodb-secret
#                  key: username
#            - name: PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: mongodb-secret
#                  key: password
            - name: MONGO_URL
              value: mongodb://mongodb-service:27017/orders

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
